
import Link from 'next/link'
import './globals.css'

export const metadata = {
  title: 'web tutorial',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html>
      <body>
        <h1><a href='/'>web</a></h1>
        <ol>
          <li><Link href='/read/1'>html</Link></li>
          <li><Link href='/read/2'>cscs</Link></li>
        </ol>
        {children}
        <ul>
          <li><Link href='/create/'>create</Link></li>
          <li><Link href='/create/1'>update</Link></li>
          <li><input type='button' value='delete'></input></li>
        </ul>
      </body>
    </html>
  )
}
